### ISSUE TITLE
"original_string" in Javascript test split is corrupted

### ISSUE THREAD

**Issue by ShushanArakelyan** [FSoft-AI4Code/TheVault#20]
Hello, thank you for collecting and posting this dataset, it is a great resource!

I was playing around with the dataset, and noticed that the "original_string" field is corrupted for Javascript/test split. I did not check any other languages or splits, maybe those also have the same issue. 
Steps to reproduce: 
```
from datasets import load_dataset
dataset = load_dataset("Fsoft-AIC/the-vault-function", split_set=["test"], languages=['JavaScript'])
print(dataset['test']['original_string'][:50])
```
output: 
> ['f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'c', 'r', '_', '_', 'd', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f']

**Comment by NamCyan** [comment]
@ShushanArakelyan sorry for late reply, thank you for pointing this out. We've fixed it, you can try again now.
