### ISSUE TITLE
Error when run test case

### ISSUE THREAD

**Issue by bunbohue19** [FSoft-AI4Code/TheVault#23]
![Screenshot from 2023-06-16 00-02-09](https://github.com/FSoft-AI4Code/TheVault/assets/95389934/bf3cb38f-1481-41ca-b61b-5250a68c502e)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 3
      1 from codetext.utils import parse_code
      2 from codetext.parser import PythonParser
----> 3 from src.utils.utils import process_raw_node
      5 code_snippet = """
      6 def sum2num(a: int, b: int):
      7   '''
   (...)
     11   return a + b # result
     12 """
     13 code_tree = parse_code(code_snippet, 'py')

File [~/TheVault/src/utils/__init__.py:1](https://file+.vscode-resource.vscode-cdn.net/home/bunbohue1906/TheVault/~/TheVault/src/utils/__init__.py:1)
----> 1 from .utils import *
      2 from .logger import create_logger

File [~/TheVault/src/utils/utils.py:15](https://file+.vscode-resource.vscode-cdn.net/home/bunbohue1906/TheVault/~/TheVault/src/utils/utils.py:15)
     13 from codetext.clean import remove_comment_delimiters
     14 from codetext.parser.language_parser import match_from_span, match_from_spans, tokenize_code, tokenize_docstring
---> 15 from utils.noise_removal.noise_removal import check_function, clean_docstring
     18 _DOCSTRING_PARSER_AVAILABLE = module_available("docstring_parser")
     20 ROOT_PATH = str(Path(__file__).parents[3])

ModuleNotFoundError: No module named 'utils'

I installed the packages in the requirements.txt file, but the file I ran raised an error. I am sure there is no wrong with the syntax

**Comment by NamCyan** [comment]
Hi @bunbohue19 , If you want to use the tool, please refer to [codetext](https://github.com/FSoft-AI4Code/CodeText-parser) repo. I believe that the module you use is not available in the current codetext version. 

If you still want to use the module try to copy the source and import requirement dependencies to new file.
