### ISSUE TITLE
More details about data

### ISSUE THREAD

**Issue by jordane95** [FSoft-AI4Code/TheVault#25]
Hi, wonerful work on code corpus! I have some problems while using the dataset.

First, when I download the dataset through the blob link, I find some data missing. For example, when I try to download rust data from the class set
```
wget https://ai4code.blob.core.windows.net/thevault/v1/class/rust.zip

--2023-08-12 23:29:39--  https://ai4code.blob.core.windows.net/thevault/v1/class/rust.zip
Resolving ai4code.blob.core.windows.net (ai4code.blob.core.windows.net)... 52.239.129.196, 52.239.129.68, 52.239.197.100
Connecting to ai4code.blob.core.windows.net (ai4code.blob.core.windows.net)|52.239.129.196|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2023-08-12 23:29:39 ERROR 404: The specified blob does not exist..
```
I'm wondering if certain source format is not included in the dataset? Or you just forgot to upload it?

In addition, when I look through the data released on huggingface, I find no distinction of different sets (class, inline, function). Are they mixed on hf?

**Comment by NamCyan** [comment]
Hi @jordane95, the class version of the dataset hasn't been public yet. The blob link currently only contains the function-level data. On huggingface you can find the function and inline versions through [Fsoft-AIC/the-vault-function](https://huggingface.co/datasets/Fsoft-AIC/the-vault-function) and [Fsoft-AIC/the-vault-inline](https://huggingface.co/datasets/Fsoft-AIC/the-vault-inline) respectively.

We will update the class version soon on Huggingface.

**Comment by jordane95** [comment]
Hi @NamCyan , would you mind uploading data files to blob link as well? Huggingface is not accessible in my country for now😟
